require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe DucksController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Duck. As you add validations to Duck, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { attributes_for(:duck) }

  let(:invalid_attributes){ {:name => ''} }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DucksController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all ducks as @ducks" do
      duck = Duck.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:ducks)).to eq([duck])
    end
  end

  describe "GET #show" do
    it "assigns the requested duck as @duck" do
      duck = Duck.create! valid_attributes
      get :show, {:id => duck.to_param}, valid_session
      expect(assigns(:duck)).to eq(duck)
    end
  end

  describe "GET #new" do
    it "assigns a new duck as @duck" do
      get :new, {}, valid_session
      expect(assigns(:duck)).to be_a_new(Duck)
    end
  end

  describe "GET #edit" do
    it "assigns the requested duck as @duck" do
      duck = Duck.create! valid_attributes
      get :edit, {:id => duck.to_param}, valid_session
      expect(assigns(:duck)).to eq(duck)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Duck" do
        expect {
          post :create, {:duck => valid_attributes}, valid_session
        }.to change(Duck, :count).by(1)
      end

      it "assigns a newly created duck as @duck" do
        post :create, {:duck => valid_attributes}, valid_session
        expect(assigns(:duck)).to be_a(Duck)
        expect(assigns(:duck)).to be_persisted
      end

      it "redirects to the created duck" do
        post :create, {:duck => valid_attributes}, valid_session
        expect(response).to redirect_to(Duck.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved duck as @duck" do
        post :create, {:duck => invalid_attributes}, valid_session
        expect(assigns(:duck)).to be_a_new(Duck)
      end

      it "re-renders the 'new' template" do
        post :create, {:duck => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) { attributes_for(:duck, :name => 'A New Name') }

      it "updates the requested duck" do
        duck = Duck.create! valid_attributes
        put :update, {:id => duck.to_param, :duck => new_attributes}, valid_session
        duck.reload
        duck.name.should == 'A New Name'
      end

      it "assigns the requested duck as @duck" do
        duck = Duck.create! valid_attributes
        put :update, {:id => duck.to_param, :duck => valid_attributes}, valid_session
        expect(assigns(:duck)).to eq(duck)
      end

      it "redirects to the duck" do
        duck = Duck.create! valid_attributes
        put :update, {:id => duck.to_param, :duck => valid_attributes}, valid_session
        expect(response).to redirect_to(duck)
      end
    end

    context "with invalid params" do
      it "assigns the duck as @duck" do
        duck = Duck.create! valid_attributes
        put :update, {:id => duck.to_param, :duck => invalid_attributes}, valid_session
        expect(assigns(:duck)).to eq(duck)
      end

      it "re-renders the 'edit' template" do
        duck = Duck.create! valid_attributes
        put :update, {:id => duck.to_param, :duck => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested duck" do
      duck = Duck.create! valid_attributes
      expect {
        delete :destroy, {:id => duck.to_param}, valid_session
      }.to change(Duck, :count).by(-1)
    end

    it "redirects to the ducks list" do
      duck = Duck.create! valid_attributes
      delete :destroy, {:id => duck.to_param}, valid_session
      expect(response).to redirect_to(ducks_url)
    end
  end

end
